//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Samples.Broker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Samples.Broker.Resources.AccountPages", typeof(AccountPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (account code of your existing active account).
        /// </summary>
        public static string AccountAdditionalAccount {
            get {
                return ResourceManager.GetString("AccountAdditionalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} account code.
        /// </summary>
        public static string AccountAdditionalAccountLabelNonNative {
            get {
                return ResourceManager.GetString("AccountAdditionalAccountLabelNonNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new address of your private wallet to receive {0}).
        /// </summary>
        public static string AccountAdditionalAddress {
            get {
                return ResourceManager.GetString("AccountAdditionalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string AccountAdditionalCreateButton {
            get {
                return ResourceManager.GetString("AccountAdditionalCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Account Created.
        /// </summary>
        public static string AccountAdditionalCreatedTabTitle {
            get {
                return ResourceManager.GetString("AccountAdditionalCreatedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your additional account has successfully been created. In a few minutes you will receive an email with an activation link..
        /// </summary>
        public static string AccountAdditionalCreatedText1 {
            get {
                return ResourceManager.GetString("AccountAdditionalCreatedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Account Created.
        /// </summary>
        public static string AccountAdditionalCreatedTitle {
            get {
                return ResourceManager.GetString("AccountAdditionalCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create additional accounts with the same bank account and trust status as an existing active account. This enables you to use multiple digital currency wallet addresses..
        /// </summary>
        public static string AccountAdditionalDesc {
            get {
                return ResourceManager.GetString("AccountAdditionalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create additional accounts with the same bank account and trust status as an existing active account. This enables you to use multiple digital currency wallet addresses..
        /// </summary>
        public static string AccountAdditionalInfoText {
            get {
                return ResourceManager.GetString("AccountAdditionalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your existing active account code.
        /// </summary>
        public static string AccountAdditionalPlaceholderAccount {
            get {
                return ResourceManager.GetString("AccountAdditionalPlaceholderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new extra {0} address.
        /// </summary>
        public static string AccountAdditionalPlaceholderAddress {
            get {
                return ResourceManager.GetString("AccountAdditionalPlaceholderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your existing active {0} account code.
        /// </summary>
        public static string AccountAdditionalPlaceholderNonNativeAccount {
            get {
                return ResourceManager.GetString("AccountAdditionalPlaceholderNonNativeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Additional Account.
        /// </summary>
        public static string AccountAdditionalTabTitle {
            get {
                return ResourceManager.GetString("AccountAdditionalTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string AccountAdditionalTitle {
            get {
                return ResourceManager.GetString("AccountAdditionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation is temporary disabled, please check back later to create additional accounts.
        /// </summary>
        public static string AccountAdditionalTitleFail {
            get {
                return ResourceManager.GetString("AccountAdditionalTitleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} address; to receive {0}.
        /// </summary>
        public static string AccountAsideAddress {
            get {
                return ResourceManager.GetString("AccountAsideAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string AccountAsideAddTitle {
            get {
                return ResourceManager.GetString("AccountAsideAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string AccountAsideBankAccountName {
            get {
                return ResourceManager.GetString("AccountAsideBankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As used on your bank account.
        /// </summary>
        public static string AccountAsideBankAccountNameDesc {
            get {
                return ResourceManager.GetString("AccountAsideBankAccountNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN bank account.
        /// </summary>
        public static string AccountAsideBankAccountNumber {
            get {
                return ResourceManager.GetString("AccountAsideBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is IBAN?.
        /// </summary>
        public static string AccountAsideBankAccountNumberHelp {
            get {
                return ResourceManager.GetString("AccountAsideBankAccountNumberHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string AccountAsideBusiness {
            get {
                return ResourceManager.GetString("AccountAsideBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank account; to receive payments.
        /// </summary>
        public static string AccountAsideCanadaAccount {
            get {
                return ResourceManager.GetString("AccountAsideCanadaAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nationality.
        /// </summary>
        public static string AccountAsideCountryCode {
            get {
                return ResourceManager.GetString("AccountAsideCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nationality.
        /// </summary>
        public static string AccountAsideCountryName {
            get {
                return ResourceManager.GetString("AccountAsideCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Account.
        /// </summary>
        public static string AccountAsideCreateAccount {
            get {
                return ResourceManager.GetString("AccountAsideCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string AccountAsideCreateButton {
            get {
                return ResourceManager.GetString("AccountAsideCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the currency of your bank account.
        /// </summary>
        public static string AccountAsideCurencySelectHelp {
            get {
                return ResourceManager.GetString("AccountAsideCurencySelectHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet address.
        /// </summary>
        public static string AccountAsideCustomerCryptoAddress {
            get {
                return ResourceManager.GetString("AccountAsideCustomerCryptoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a wallet?.
        /// </summary>
        public static string AccountAsideCustomerCryptoAddressHelp {
            get {
                return ResourceManager.GetString("AccountAsideCustomerCryptoAddressHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} address of your private wallet.
        /// </summary>
        public static string AccountAsideCustomerCryptoAddressPlaceholder {
            get {
                return ResourceManager.GetString("AccountAsideCustomerCryptoAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy crypto and sell crypto directly after creating an account. You can link multiple crypto addresses to one account..
        /// </summary>
        public static string AccountAsideDesc {
            get {
                return ResourceManager.GetString("AccountAsideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address; to receive email confirmations.
        /// </summary>
        public static string AccountAsideEmail {
            get {
                return ResourceManager.GetString("AccountAsideEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IBAN bank account; to receive payments.
        /// </summary>
        public static string AccountAsideIBAN {
            get {
                return ResourceManager.GetString("AccountAsideIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type account.
        /// </summary>
        public static string AccountAsideIsBusiness {
            get {
                return ResourceManager.GetString("AccountAsideIsBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string AccountAsideIsBusinessHelp {
            get {
                return ResourceManager.GetString("AccountAsideIsBusinessHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string AccountAsideMail {
            get {
                return ResourceManager.GetString("AccountAsideMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name; as used on your bank account.
        /// </summary>
        public static string AccountAsideName {
            get {
                return ResourceManager.GetString("AccountAsideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that for {0} you need an already existing {1} account..
        /// </summary>
        public static string AccountAsideNonNativeDesc {
            get {
                return ResourceManager.GetString("AccountAsideNonNativeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string AccountAsideNonSWIFT {
            get {
                return ResourceManager.GetString("AccountAsideNonSWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string AccountAsidePersonal {
            get {
                return ResourceManager.GetString("AccountAsidePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} address of your private wallet.
        /// </summary>
        public static string AccountAsidePlaceholderAddress {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your nationality.
        /// </summary>
        public static string AccountAsidePlaceholderCountryName {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string AccountAsidePlaceholderEmail {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank account.
        /// </summary>
        public static string AccountAsidePlaceholderIBAN {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string AccountAsidePlaceholderName {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank account.
        /// </summary>
        public static string AccountAsidePlaceholderSwiftAccount {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderSwiftAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank SWIFT code.
        /// </summary>
        public static string AccountAsidePlaceholderSwiftCode {
            get {
                return ResourceManager.GetString("AccountAsidePlaceholderSwiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Code:.
        /// </summary>
        public static string AccountAsideReferralCode {
            get {
                return ResourceManager.GetString("AccountAsideReferralCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        public static string AccountAsideSWIFT {
            get {
                return ResourceManager.GetString("AccountAsideSWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank SWIFT code; to receive payments.
        /// </summary>
        public static string AccountAsideSwiftCode {
            get {
                return ResourceManager.GetString("AccountAsideSwiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently only Canada supported..
        /// </summary>
        public static string AccountAsideSwiftOptionHelp {
            get {
                return ResourceManager.GetString("AccountAsideSwiftOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the {0} and to the {1}.
        /// </summary>
        public static string AccountAsideTermsAgree {
            get {
                return ResourceManager.GetString("AccountAsideTermsAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string AccountAsideTermsLink {
            get {
                return ResourceManager.GetString("AccountAsideTermsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new address to your existing account.
        /// </summary>
        public static string AccountAsideTitle {
            get {
                return ResourceManager.GetString("AccountAsideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a .
        /// </summary>
        public static string AccountAsideWallet {
            get {
                return ResourceManager.GetString("AccountAsideWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Wallet.
        /// </summary>
        public static string AccountAsideWalletLink {
            get {
                return ResourceManager.GetString("AccountAsideWalletLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;Account creation is temporary disabled, please check back later to create your new account.
        /// </summary>
        public static string AccountAsideWarningText {
            get {
                return ResourceManager.GetString("AccountAsideWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Created.
        /// </summary>
        public static string AccountCreatedTabTitle {
            get {
                return ResourceManager.GetString("AccountCreatedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has successfully been created..
        /// </summary>
        public static string AccountCreatedText1 {
            get {
                return ResourceManager.GetString("AccountCreatedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Created.
        /// </summary>
        public static string AccountCreatedTitle {
            get {
                return ResourceManager.GetString("AccountCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (account code of active account to delete).
        /// </summary>
        public static string AccountDeleteAccount {
            get {
                return ResourceManager.GetString("AccountDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AccountDeleteConfirmButton {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (bank account).
        /// </summary>
        public static string AccountDeleteConfirmIBAN {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (name of bank account holder).
        /// </summary>
        public static string AccountDeleteConfirmName {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (your address to receive {0}).
        /// </summary>
        public static string AccountDeleteConfirmReceiveAddress {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmReceiveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (address to sell {0}).
        /// </summary>
        public static string AccountDeleteConfirmSellAddress {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmSellAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Account Delete.
        /// </summary>
        public static string AccountDeleteConfirmTabTitle {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not active, it is either invalid or already deleted..
        /// </summary>
        public static string AccountDeleteConfirmTextFail {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmTextFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the deletion of account.
        /// </summary>
        public static string AccountDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Account.
        /// </summary>
        public static string AccountDeleteConfirmTitleFail {
            get {
                return ResourceManager.GetString("AccountDeleteConfirmTitleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deleted.
        /// </summary>
        public static string AccountDeletedTabTitle {
            get {
                return ResourceManager.GetString("AccountDeletedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has beent sent to:.
        /// </summary>
        public static string AccountDeletedText1 {
            get {
                return ResourceManager.GetString("AccountDeletedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail reason:.
        /// </summary>
        public static string AccountDeletedText2 {
            get {
                return ResourceManager.GetString("AccountDeletedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Succesfully Deleted.
        /// </summary>
        public static string AccountDeletedTitle {
            get {
                return ResourceManager.GetString("AccountDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete your account.
        /// </summary>
        public static string AccountDeletedTitleFail {
            get {
                return ResourceManager.GetString("AccountDeletedTitleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (email address connected to this account).
        /// </summary>
        public static string AccountDeleteEmail {
            get {
                return ResourceManager.GetString("AccountDeleteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and an account code to request for deletion of an active account. You will recieve an email with a confirmation link to delete the account..
        /// </summary>
        public static string AccountDeleteInfoText {
            get {
                return ResourceManager.GetString("AccountDeleteInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account code.
        /// </summary>
        public static string AccountDeletePlaceholderAccount {
            get {
                return ResourceManager.GetString("AccountDeletePlaceholderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string AccountDeletePlaceholderEmail {
            get {
                return ResourceManager.GetString("AccountDeletePlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request delete.
        /// </summary>
        public static string AccountDeleteRequestButton {
            get {
                return ResourceManager.GetString("AccountDeleteRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete request failed:.
        /// </summary>
        public static string AccountDeleteRequestedFailed {
            get {
                return ResourceManager.GetString("AccountDeleteRequestedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Delete Requested.
        /// </summary>
        public static string AccountDeleteRequestedTabTitle {
            get {
                return ResourceManager.GetString("AccountDeleteRequestedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a few minutes you will receive an email with a delete confirmation link at the submitted email address:.
        /// </summary>
        public static string AccountDeleteRequestedText1 {
            get {
                return ResourceManager.GetString("AccountDeleteRequestedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (if the requested account is known and active and uses this email address).
        /// </summary>
        public static string AccountDeleteRequestedText2 {
            get {
                return ResourceManager.GetString("AccountDeleteRequestedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Delete Requested.
        /// </summary>
        public static string AccountDeleteRequestedTitle {
            get {
                return ResourceManager.GetString("AccountDeleteRequestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string AccountDeleteTabTitle {
            get {
                return ResourceManager.GetString("AccountDeleteTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an Account.
        /// </summary>
        public static string AccountDeleteTitle {
            get {
                return ResourceManager.GetString("AccountDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (email address to recieve your account details).
        /// </summary>
        public static string AccountInfoEmail {
            get {
                return ResourceManager.GetString("AccountInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can request to receive an email with the details of your currently active accounts..
        /// </summary>
        public static string AccountInfoInfoText {
            get {
                return ResourceManager.GetString("AccountInfoInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string AccountInfoPlaceholderEmail {
            get {
                return ResourceManager.GetString("AccountInfoPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request email.
        /// </summary>
        public static string AccountInfoRequestButton {
            get {
                return ResourceManager.GetString("AccountInfoRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info Requested.
        /// </summary>
        public static string AccountInfoRequestedTabTitle {
            get {
                return ResourceManager.GetString("AccountInfoRequestedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a few minutes you will receive an email with active account information at the submitted email address:.
        /// </summary>
        public static string AccountInfoRequestedText11 {
            get {
                return ResourceManager.GetString("AccountInfoRequestedText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (if at least one active account exists using this email address).
        /// </summary>
        public static string AccountInfoRequestedText12 {
            get {
                return ResourceManager.GetString("AccountInfoRequestedText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail reason:.
        /// </summary>
        public static string AccountInfoRequestedText21 {
            get {
                return ResourceManager.GetString("AccountInfoRequestedText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info Email Requested.
        /// </summary>
        public static string AccountInfoRequestedTitle {
            get {
                return ResourceManager.GetString("AccountInfoRequestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info Request Failed.
        /// </summary>
        public static string AccountInfoRequestedTitleFail {
            get {
                return ResourceManager.GetString("AccountInfoRequestedTitleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Account Info.
        /// </summary>
        public static string AccountInfoTabTitle {
            get {
                return ResourceManager.GetString("AccountInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Account Info.
        /// </summary>
        public static string AccountInfoTitle {
            get {
                return ResourceManager.GetString("AccountInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name Updated.
        /// </summary>
        public static string AccountNameUpdatedTabTitle {
            get {
                return ResourceManager.GetString("AccountNameUpdatedTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name Updated.
        /// </summary>
        public static string AccountNameUpdatedTitle {
            get {
                return ResourceManager.GetString("AccountNameUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account name has not been updated, failure reason:.
        /// </summary>
        public static string AccountNameUpdateFail {
            get {
                return ResourceManager.GetString("AccountNameUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account name has been updated successful..
        /// </summary>
        public static string AccountNameUpdateSuccess {
            get {
                return ResourceManager.GetString("AccountNameUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string AccountPageActivateTabTitle {
            get {
                return ResourceManager.GetString("AccountPageActivateTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Account.
        /// </summary>
        public static string AccountPageAdditionalLink {
            get {
                return ResourceManager.GetString("AccountPageAdditionalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Accounts.
        /// </summary>
        public static string AccountPageBusinessAccount {
            get {
                return ResourceManager.GetString("AccountPageBusinessAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Business Accounts verification is required..
        /// </summary>
        public static string AccountPageBusinessInfo1 {
            get {
                return ResourceManager.GetString("AccountPageBusinessInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;NEW&lt;/b&gt;: Only test transactions available.
        /// </summary>
        public static string AccountPageBusinessInfo2 {
            get {
                return ResourceManager.GetString("AccountPageBusinessInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;VERIFIED&lt;/b&gt;: multiple buy transactions per day up to a maximum of 5000 euro per transaction. To request for business verification procedure:.
        /// </summary>
        public static string AccountPageBusinessInfo3 {
            get {
                return ResourceManager.GetString("AccountPageBusinessInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Forgotten your Account?&lt;/b&gt; You can request for an email with the Account info of all your active Accounts:.
        /// </summary>
        public static string AccountPageExtraInfo1 {
            get {
                return ResourceManager.GetString("AccountPageExtraInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add new {0} wallet addresses by creating &lt;b&gt;Additional Accounts&lt;/b&gt; using the same details and trust level of an exisiting account:.
        /// </summary>
        public static string AccountPageExtraInfo2 {
            get {
                return ResourceManager.GetString("AccountPageExtraInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &lt;b&gt;IBAN bank account number&lt;/b&gt; contains a maximum of 34 alphanumerical characters and begins with the country code, like NL01RABO0123456789. To translate your normal bank account number to an IBAN code, you can use a tool like &lt;a href=&quot;http://www.ibancalculator.com&quot; target=&quot;_blank&quot;&gt;IBAN Calculator&lt;/a&gt;.
        /// </summary>
        public static string AccountPageExtraInfo3 {
            get {
                return ResourceManager.GetString("AccountPageExtraInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;b&gt;SWIFT or BIC code &lt;/b&gt; contains 8 or 11 alphanumeric characters and is a standard format of Bank Identifier Code (BIC). The SWIFT code is an unique identification code for a particular bank. Please consult your bank or online services
        ///such as &lt;a href=&quot;http://www.theswiftcodes.com/&quot;&gt;The SWIFT Codes &lt;/a&gt;  for your bank SWIFT code..
        /// </summary>
        public static string AccountPageExtraInfo4 {
            get {
                return ResourceManager.GetString("AccountPageExtraInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need fast track?.
        /// </summary>
        public static string AccountPageFastTrackLink {
            get {
                return ResourceManager.GetString("AccountPageFastTrackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy {0} and sell {0} directly after creating a Account. HERMESworks with Accounts to provide you with additional security. It also gives you a &apos;one-click&apos; ordering method, which speeds up the process and helps you avoiding errors. Your account is only used for these purposes. HERMES does not keep or manage any Crypto wallets and/or Euro deposits..
        /// </summary>
        public static string AccountPageInfo1 {
            get {
                return ResourceManager.GetString("AccountPageInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account you use when creating a Account determines the type of your Account. If you use a personal bank account, select &apos;Personal&apos; when creating a New Account. However, if you intend to use a business bank account, you need to select &apos;Business&apos;..
        /// </summary>
        public static string AccountPageInfo2 {
            get {
                return ResourceManager.GetString("AccountPageInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Account Info.
        /// </summary>
        public static string AccountPageInfoLink {
            get {
                return ResourceManager.GetString("AccountPageInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Account.
        /// </summary>
        public static string AccountPageManageAccount {
            get {
                return ResourceManager.GetString("AccountPageManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Accounts.
        /// </summary>
        public static string AccountPagePersonalAccount {
            get {
                return ResourceManager.GetString("AccountPagePersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;NEW&lt;/b&gt;: during first week after your first buy transaction (not test transaction). To bypass the one week transaction limit for New Accounts, HERMES offers a &apos;fast track&apos; confirmation procedure:.
        /// </summary>
        public static string AccountPagePersonalInfo1 {
            get {
                return ResourceManager.GetString("AccountPagePersonalInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TRUSTED&lt;/b&gt;: automatic upgrade from New Account one week after the first buy transaction (not test transaction)..
        /// </summary>
        public static string AccountPagePersonalInfo3 {
            get {
                return ResourceManager.GetString("AccountPagePersonalInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;VERIFIED&lt;/b&gt;: on request - authenticity of identity and proof of residence required. To request for personal verification procedure:.
        /// </summary>
        public static string AccountPagePersonalInfo4 {
            get {
                return ResourceManager.GetString("AccountPagePersonalInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Sofort Banking, GiroPay and MyBank are limited to 1000 EUR equivalent per day..
        /// </summary>
        public static string AccountPageTabBuyExtra {
            get {
                return ResourceManager.GetString("AccountPageTabBuyExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy limits (per day / per month).
        /// </summary>
        public static string AccountPageTabBuyHeader {
            get {
                return ResourceManager.GetString("AccountPageTabBuyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status.
        /// </summary>
        public static string AccountPageTabBuyText11 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string AccountPageTabBuyText12 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string AccountPageTabBuyText13 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string AccountPageTabBuyText21 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted.
        /// </summary>
        public static string AccountPageTabBuyText41 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string AccountPageTabBuyText51 {
            get {
                return ResourceManager.GetString("AccountPageTabBuyText51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string AccountPageTabBuyTitle {
            get {
                return ResourceManager.GetString("AccountPageTabBuyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell limits (per day / per month).
        /// </summary>
        public static string AccountPageTabSellHeader {
            get {
                return ResourceManager.GetString("AccountPageTabSellHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status.
        /// </summary>
        public static string AccountPageTabSellText11 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string AccountPageTabSellText12 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string AccountPageTabSellText13 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string AccountPageTabSellText21 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed.
        /// </summary>
        public static string AccountPageTabSellText23 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted.
        /// </summary>
        public static string AccountPageTabSellText41 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string AccountPageTabSellText51 {
            get {
                return ResourceManager.GetString("AccountPageTabSellText51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string AccountPageTabSellTitle {
            get {
                return ResourceManager.GetString("AccountPageTabSellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string AccountPageTabTitle {
            get {
                return ResourceManager.GetString("AccountPageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountPageTitle {
            get {
                return ResourceManager.GetString("AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need verification?.
        /// </summary>
        public static string AccountPageVerificationLink {
            get {
                return ResourceManager.GetString("AccountPageVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want account verification?.
        /// </summary>
        public static string AccountPageWantVerificationLink {
            get {
                return ResourceManager.GetString("AccountPageWantVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your address (street + number).
        /// </summary>
        public static string AccountUpdateAddress {
            get {
                return ResourceManager.GetString("AccountUpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your city.
        /// </summary>
        public static string AccountUpdateCity {
            get {
                return ResourceManager.GetString("AccountUpdateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your country.
        /// </summary>
        public static string AccountUpdateCountryName {
            get {
                return ResourceManager.GetString("AccountUpdateCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current name:.
        /// </summary>
        public static string AccountUpdateCurrentName {
            get {
                return ResourceManager.GetString("AccountUpdateCurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your account details as they are marked by our system as incomplete or unlikely. Only when we have the same full name and address details as you use with your bank account, we can successfully payout your sell transactions..
        /// </summary>
        public static string AccountUpdateInfo1 {
            get {
                return ResourceManager.GetString("AccountUpdateInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name.
        /// </summary>
        public static string AccountUpdateName {
            get {
                return ResourceManager.GetString("AccountUpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string AccountUpdateNameButton {
            get {
                return ResourceManager.GetString("AccountUpdateNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your account name. It was marked by our system as incomplete or unlikely..
        /// </summary>
        public static string AccountUpdateNameInfo1a {
            get {
                return ResourceManager.GetString("AccountUpdateNameInfo1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when we have the same full name as you use with your bank account, we can successfully payout your sell transactions..
        /// </summary>
        public static string AccountUpdateNameInfo1b {
            get {
                return ResourceManager.GetString("AccountUpdateNameInfo1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested account is unknown or invalid or the account name has already been updated..
        /// </summary>
        public static string AccountUpdateNameTextFail {
            get {
                return ResourceManager.GetString("AccountUpdateNameTextFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Name.
        /// </summary>
        public static string AccountUpdateNameTitle {
            get {
                return ResourceManager.GetString("AccountUpdateNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account name.
        /// </summary>
        public static string AccountUpdateNewName {
            get {
                return ResourceManager.GetString("AccountUpdateNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Details.
        /// </summary>
        public static string AccountUpdateTabTitle {
            get {
                return ResourceManager.GetString("AccountUpdateTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Details.
        /// </summary>
        public static string AccountUpdateTitle {
            get {
                return ResourceManager.GetString("AccountUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your zipcode.
        /// </summary>
        public static string AccountUpdateZipCode {
            get {
                return ResourceManager.GetString("AccountUpdateZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully activated your account.
        /// </summary>
        public static string CONTROLMESSAGE001 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business account {0} is now activated. Within a few minutes you will receive an email with your account details. Before you can use a business account to buy and sell, it needs to be verified..
        /// </summary>
        public static string CONTROLMESSAGE002 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal account {0} is now activated. Within a few minutes you will receive an email with your account details..
        /// </summary>
        public static string CONTROLMESSAGE003 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can use this account to buy and sell {0}, it needs to be verified..
        /// </summary>
        public static string CONTROLMESSAGE004 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate your account.
        /// </summary>
        public static string CONTROLMESSAGE005 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string CONTROLMESSAGE006 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code and email fields must both have a value.
        /// </summary>
        public static string CONTROLMESSAGE007 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string CONTROLMESSAGE008 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or empty account name.
        /// </summary>
        public static string CONTROLMESSAGE009 {
            get {
                return ResourceManager.GetString("CONTROLMESSAGE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN already in use.
        /// </summary>
        public static string CustomerExists {
            get {
                return ResourceManager.GetString("CustomerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name is required.
        /// </summary>
        public static string ERRORMESSAGE_HC_COUNTRYREQUIRED {
            get {
                return ResourceManager.GetString("ERRORMESSAGE_HC_COUNTRYREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link has already been used. Did you activate your account already?.
        /// </summary>
        public static string ERRORMESSAGE001 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of accounts currently disabled.
        /// </summary>
        public static string ERRORMESSAGE002 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is already in use, do you want to add an extra {0} address? &lt;br /&gt;&lt;a href=&quot;/en/account/createadditional&quot;&gt;&gt; Additional account&lt;/a&gt;.
        /// </summary>
        public static string ERRORMESSAGE003 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or not active account.
        /// </summary>
        public static string ERRORMESSAGE004 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create additional account: missing active bank account.
        /// </summary>
        public static string ERRORMESSAGE005 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} address is required.
        /// </summary>
        public static string ERRORMESSAGE006 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} address.
        /// </summary>
        public static string ERRORMESSAGE007 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} address already used before.
        /// </summary>
        public static string ERRORMESSAGE008 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string ERRORMESSAGE009 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is already active.
        /// </summary>
        public static string ERRORMESSAGE010 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not a valid account (probably it is outdated or it was invalidated by requesting a newer account).
        /// </summary>
        public static string ERRORMESSAGE011 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not active.
        /// </summary>
        public static string ERRORMESSAGE012 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string ERRORMESSAGE013 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string ERRORMESSAGE014 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN is required.
        /// </summary>
        public static string ERRORMESSAGE015 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IBAN code.
        /// </summary>
        public static string ERRORMESSAGE016 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This IBAN is in a range that cannot be served.
        /// </summary>
        public static string ERRORMESSAGE017 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined country in IBAN code.
        /// </summary>
        public static string ERRORMESSAGE018 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is not associated with this labelpartner.
        /// </summary>
        public static string ERRORMESSAGE019 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account holder name is required.
        /// </summary>
        public static string ERRORMESSAGE020 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not agree to the Terms of Use.
        /// </summary>
        public static string ERRORMESSAGE022 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or Inactive referral code.
        /// </summary>
        public static string ERRORMESSAGE023 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many accounts, please wait 24 hours.
        /// </summary>
        public static string ERRORMESSAGE024 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT code required.
        /// </summary>
        public static string ERRORMESSAGE065 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SWIFT code.
        /// </summary>
        public static string ERRORMESSAGE066 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SWIFT code is in a range that cannot be served.
        /// </summary>
        public static string ERRORMESSAGE067 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined country in SWIFT code.
        /// </summary>
        public static string ERRORMESSAGE068 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account is required.
        /// </summary>
        public static string ERRORMESSAGE069 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bank Account.
        /// </summary>
        public static string ERRORMESSAGE070 {
            get {
                return ResourceManager.GetString("ERRORMESSAGE070", resourceCulture);
            }
        }
    }
}
