//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Samples.Broker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuyPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuyPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Samples.Broker.Resources.BuyPages", typeof(BuyPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or inactive account.
        /// </summary>
        public static string AccountNotActivated {
            get {
                return ResourceManager.GetString("AccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or inactive account.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account:.
        /// </summary>
        public static string BankInfoAccountDetail01 {
            get {
                return ResourceManager.GetString("BankInfoAccountDetail01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank country:.
        /// </summary>
        public static string BankInfoAccountDetail02 {
            get {
                return ResourceManager.GetString("BankInfoAccountDetail02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account:.
        /// </summary>
        public static string BankInfoAccountDetail03 {
            get {
                return ResourceManager.GetString("BankInfoAccountDetail03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account holder:.
        /// </summary>
        public static string BankInfoAccountDetail04 {
            get {
                return ResourceManager.GetString("BankInfoAccountDetail04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details.
        /// </summary>
        public static string BankInfoAccountDetails {
            get {
                return ResourceManager.GetString("BankInfoAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: The BIC code of your bank should be 8 or 11 characters long and contains your bank country code!.
        /// </summary>
        public static string BankInfoBicAttention {
            get {
                return ResourceManager.GetString("BankInfoBicAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BIC code of your bank is:.
        /// </summary>
        public static string BankInfoBicInfoLine01 {
            get {
                return ResourceManager.GetString("BankInfoBicInfoLine01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update also the following bank details:.
        /// </summary>
        public static string BankInfoBicInfoLine02 {
            get {
                return ResourceManager.GetString("BankInfoBicInfoLine02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To initiate your first buy transaction we need to know the BIC/SWIFT code of your bank. This code is an unique identification code for a particular bank and are used when transferring money between banks, particularly for international wire transfers. The BIC/SWIFT codes consist of 8 or 11 characters. You can find the BIC code of your bank on the homepage of your bank or by using an online tool like &lt;a href=&quot;http://www.ibancalculator.com/iban_validieren.html&quot; target=&quot;_blank&quot;&gt;IBAN Calculator&lt;/a&gt;..
        /// </summary>
        public static string BankInfoBicMessage01 {
            get {
                return ResourceManager.GetString("BankInfoBicMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can only process payments where the BIC code of your bank is consistent with the IBAN code of your bank account..
        /// </summary>
        public static string BankInfoBicMessage02 {
            get {
                return ResourceManager.GetString("BankInfoBicMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK.
        /// </summary>
        public static string BankInfoButtonCheck {
            get {
                return ResourceManager.GetString("BankInfoButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string BankInfoButtonSave {
            get {
                return ResourceManager.GetString("BankInfoButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name.
        /// </summary>
        public static string BankInfoEditSpanBank {
            get {
                return ResourceManager.GetString("BankInfoEditSpanBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC code of your bank.
        /// </summary>
        public static string BankInfoEditSpanBic {
            get {
                return ResourceManager.GetString("BankInfoEditSpanBic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank city or region.
        /// </summary>
        public static string BankInfoEditSpanCity {
            get {
                return ResourceManager.GetString("BankInfoEditSpanCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Bank Information.
        /// </summary>
        public static string BankInfoPageTabTitle {
            get {
                return ResourceManager.GetString("BankInfoPageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Bank Information.
        /// </summary>
        public static string BankInfoPageTitle {
            get {
                return ResourceManager.GetString("BankInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name.
        /// </summary>
        public static string BankInfoPlaceHolderBank {
            get {
                return ResourceManager.GetString("BankInfoPlaceHolderBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string BankInfoPlaceHolderCity {
            get {
                return ResourceManager.GetString("BankInfoPlaceHolderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Account holders in the Single Euro Payments Area (SEPA) without access to an instant payment method can buy {0} by bank transfer. The {0} price is equal to the actual market price at the time your transaction is processed after receiving confirmation from our bank of your transfer..
        /// </summary>
        public static string BuyBankTransferText1 {
            get {
                return ResourceManager.GetString("BuyBankTransferText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to initiate your bank transfer from the same bank account as is connected to your Account and to put your Account code in the comment field of the bank transaction! The bank account details for initiating a bank transfer are displayed when reviewing your order..
        /// </summary>
        public static string BuyBankTransferText2 {
            get {
                return ResourceManager.GetString("BuyBankTransferText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {0} by European bank transfer (SEPA).
        /// </summary>
        public static string BuyBankTransferTitle {
            get {
                return ResourceManager.GetString("BuyBankTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or inactive account.
        /// </summary>
        public static string BUYERRORCODE001 {
            get {
                return ResourceManager.GetString("BUYERRORCODE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment method available for this account.
        /// </summary>
        public static string BUYERRORCODE002 {
            get {
                return ResourceManager.GetString("BUYERRORCODE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment method available.
        /// </summary>
        public static string BUYERRORCODE003 {
            get {
                return ResourceManager.GetString("BUYERRORCODE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method type unknown.
        /// </summary>
        public static string BUYERRORCODE004 {
            get {
                return ResourceManager.GetString("BUYERRORCODE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is currently not active.
        /// </summary>
        public static string BUYERRORCODE005 {
            get {
                return ResourceManager.GetString("BUYERRORCODE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is currently not active.
        /// </summary>
        public static string BUYERRORCODE006 {
            get {
                return ResourceManager.GetString("BUYERRORCODE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction buy value too small.
        /// </summary>
        public static string BUYERRORCODE007 {
            get {
                return ResourceManager.GetString("BUYERRORCODE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction buy value too large.
        /// </summary>
        public static string BUYERRORCODE008 {
            get {
                return ResourceManager.GetString("BUYERRORCODE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated transaction buy value exceeding daily limit.
        /// </summary>
        public static string BUYERRORCODE009 {
            get {
                return ResourceManager.GetString("BUYERRORCODE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction currently not possible, buying transactions have been disabled.
        /// </summary>
        public static string BUYERRORCODE010 {
            get {
                return ResourceManager.GetString("BUYERRORCODE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save transaction record.
        /// </summary>
        public static string BUYERRORCODE011 {
            get {
                return ResourceManager.GetString("BUYERRORCODE011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save payment information.
        /// </summary>
        public static string BUYERRORCODE012 {
            get {
                return ResourceManager.GetString("BUYERRORCODE012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method is limited. Please try another payment method for larger amounts..
        /// </summary>
        public static string BUYERRORCODE013 {
            get {
                return ResourceManager.GetString("BUYERRORCODE013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected payment method failed to initiate a transaction, please contact support.
        /// </summary>
        public static string BUYERRORCODE014 {
            get {
                return ResourceManager.GetString("BUYERRORCODE014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only initiate one test transaction per day.
        /// </summary>
        public static string BUYERRORCODE015 {
            get {
                return ResourceManager.GetString("BUYERRORCODE015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated transaction buy value exceeding monthy limit.
        /// </summary>
        public static string BUYERRORCODE016 {
            get {
                return ResourceManager.GetString("BUYERRORCODE016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use GiroPay our payment processor requires us to collect an Id of the clients. To activate this payment option please send a photo of your passport, id-card or drivers license..
        /// </summary>
        public static string BUYERRORCODE017 {
            get {
                return ResourceManager.GetString("BUYERRORCODE017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string BuyFormAccount {
            get {
                return ResourceManager.GetString("BuyFormAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code.
        /// </summary>
        public static string BuyFormAccountLabel {
            get {
                return ResourceManager.GetString("BuyFormAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account code.
        /// </summary>
        public static string BuyFormAccountPlaceHolder {
            get {
                return ResourceManager.GetString("BuyFormAccountPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available maximum amount depends on your Account status..
        /// </summary>
        public static string BuyFormAmountHelp {
            get {
                return ResourceManager.GetString("BuyFormAmountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string BuyFormAmountLabel {
            get {
                return ResourceManager.GetString("BuyFormAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank fee.
        /// </summary>
        public static string BuyFormBankFeeLabel {
            get {
                return ResourceManager.GetString("BuyFormBankFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string BuyFormCheckAccountButton {
            get {
                return ResourceManager.GetString("BuyFormCheckAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully completed your first buy transaction. As soon as your payment has arrived on our bank account your limit will be increased. This will typically take one working-day. Thanks for your understanding..
        /// </summary>
        public static string BuyFormCoolDown {
            get {
                return ResourceManager.GetString("BuyFormCoolDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daily buy limit..
        /// </summary>
        public static string BuyFormDailyLimitMessage {
            get {
                return ResourceManager.GetString("BuyFormDailyLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofort-Payment Service is currently not available for German Sparkassen accounts. GiroPay and SEPA are both available..
        /// </summary>
        public static string BuyFormGermanyNotice {
            get {
                return ResourceManager.GetString("BuyFormGermanyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is high risk customer..
        /// </summary>
        public static string BuyFormHighRisk {
            get {
                return ResourceManager.GetString("BuyFormHighRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is incasso customer..
        /// </summary>
        public static string BuyFormIncasso {
            get {
                return ResourceManager.GetString("BuyFormIncasso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited business account.
        /// </summary>
        public static string BuyFormLimitedBusinessMessage {
            get {
                return ResourceManager.GetString("BuyFormLimitedBusinessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is this account limited?.
        /// </summary>
        public static string BuyFormLimitedInfoLink {
            get {
                return ResourceManager.GetString("BuyFormLimitedInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited personal account.
        /// </summary>
        public static string BuyFormLimitedPersonalMessage {
            get {
                return ResourceManager.GetString("BuyFormLimitedPersonalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum buy amount is limited due to:.
        /// </summary>
        public static string BuyFormLimitReasonTitle {
            get {
                return ResourceManager.GetString("BuyFormLimitReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low {0} reserves..
        /// </summary>
        public static string BuyFormLowBalanceMessage {
            get {
                return ResourceManager.GetString("BuyFormLowBalanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has not initiated a Buy transaction..
        /// </summary>
        public static string BuyFormMissingBuyTransaction {
            get {
                return ResourceManager.GetString("BuyFormMissingBuyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monthly buy limit..
        /// </summary>
        public static string BuyFormMonthlyLimitMessage {
            get {
                return ResourceManager.GetString("BuyFormMonthlyLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need fast-track upgrade?.
        /// </summary>
        public static string BuyFormNeedFastTrackLink {
            get {
                return ResourceManager.GetString("BuyFormNeedFastTrackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you can only initiate test transactions. To increase your limits you need to upload your FotoID. After it has been checked your limit will be increased. This will typically take one working-day. Thanks for your understanding..
        /// </summary>
        public static string BuyFormNeedFotoID {
            get {
                return ResourceManager.GetString("BuyFormNeedFotoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need account verification?.
        /// </summary>
        public static string BuyFormNeedVerificationLink {
            get {
                return ResourceManager.GetString("BuyFormNeedVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the fee that’s paid to the crypto miners to confirm your transaction.
        /// </summary>
        public static string BuyFormNetworkFeeHelp {
            get {
                return ResourceManager.GetString("BuyFormNetworkFeeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner fee.
        /// </summary>
        public static string BuyFormNetworkFeeLabel {
            get {
                return ResourceManager.GetString("BuyFormNetworkFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified Business Account..
        /// </summary>
        public static string BuyFormNewBusiness {
            get {
                return ResourceManager.GetString("BuyFormNewBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New business account.
        /// </summary>
        public static string BuyFormNewBusinessMessage {
            get {
                return ResourceManager.GetString("BuyFormNewBusinessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW customers must provide a photo id..
        /// </summary>
        public static string BuyFormNewCustomerNoFotoId {
            get {
                return ResourceManager.GetString("BuyFormNewCustomerNoFotoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Personal Account..
        /// </summary>
        public static string BuyFormNewPersonal {
            get {
                return ResourceManager.GetString("BuyFormNewPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New personal account.
        /// </summary>
        public static string BuyFormNewPersonalMessage {
            get {
                return ResourceManager.GetString("BuyFormNewPersonalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First buy transaction is still unsettled..
        /// </summary>
        public static string BuyFormNewUnsettled {
            get {
                return ResourceManager.GetString("BuyFormNewUnsettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code?.
        /// </summary>
        public static string BuyFormNoActiveAccountLink {
            get {
                return ResourceManager.GetString("BuyFormNoActiveAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balance available..
        /// </summary>
        public static string BuyFormNoBalance {
            get {
                return ResourceManager.GetString("BuyFormNoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an active Account!.
        /// </summary>
        public static string BuyFormNonActiveAccount {
            get {
                return ResourceManager.GetString("BuyFormNonActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference price available..
        /// </summary>
        public static string BuyFormNoReferencePrice {
            get {
                return ResourceManager.GetString("BuyFormNoReferencePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment you can only initiate test transactions, because we did not receive the payment of at least one earlier buy transaction. Please contact your bank; probably your payment order was not fulfilled by your bank or your bank performed a refund. For questions you can contact the support team..
        /// </summary>
        public static string BuyFormPaymentPending {
            get {
                return ResourceManager.GetString("BuyFormPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using instant payment methods like iDEAL, Bancontact Mister Cash, GiroPay, Sofort or Interac you will receive {0} within minutes. SEPA banktransfers take at least one working day..
        /// </summary>
        public static string BuyFormPayMethodHelp {
            get {
                return ResourceManager.GetString("BuyFormPayMethodHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string BuyFormPayMethodLabel {
            get {
                return ResourceManager.GetString("BuyFormPayMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string BuyFormPurchaseLabel {
            get {
                return ResourceManager.GetString("BuyFormPurchaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount is higher than available reserve..
        /// </summary>
        public static string BuyFormRequestedHigherThanAvailableAmount {
            get {
                return ResourceManager.GetString("BuyFormRequestedHigherThanAvailableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount is higher than maximum..
        /// </summary>
        public static string BuyFormRequestedHigherThanMaximum {
            get {
                return ResourceManager.GetString("BuyFormRequestedHigherThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested amount is lower than minimum..
        /// </summary>
        public static string BuyFormRequestedLowerThanMinimum {
            get {
                return ResourceManager.GetString("BuyFormRequestedLowerThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review order.
        /// </summary>
        public static string BuyFormReviewButton {
            get {
                return ResourceManager.GetString("BuyFormReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee.
        /// </summary>
        public static string BuyFormServiceFeeLabel {
            get {
                return ResourceManager.GetString("BuyFormServiceFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string BuyFormSubTotalLabel {
            get {
                return ResourceManager.GetString("BuyFormSubTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can start to buy {0}, you first need to complete the small test buy transaction below. This is to verify your banking details..
        /// </summary>
        public static string BuyFormTestTransactionNeeded {
            get {
                return ResourceManager.GetString("BuyFormTestTransactionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Personal Account..
        /// </summary>
        public static string BuyFormTrustedPersonal {
            get {
                return ResourceManager.GetString("BuyFormTrustedPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business in unidentified..
        /// </summary>
        public static string BuyFormUnidentifiedBusiness {
            get {
                return ResourceManager.GetString("BuyFormUnidentifiedBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Business Account..
        /// </summary>
        public static string BuyFormVerifiedBusiness {
            get {
                return ResourceManager.GetString("BuyFormVerifiedBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Personal Account..
        /// </summary>
        public static string BuyFormVerifiedPersonal {
            get {
                return ResourceManager.GetString("BuyFormVerifiedPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid {0} account.
        /// </summary>
        public static string BuyFormWrongCoinAccount {
            get {
                return ResourceManager.GetString("BuyFormWrongCoinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string BUYINFOCODE01 {
            get {
                return ResourceManager.GetString("BUYINFOCODE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying price.
        /// </summary>
        public static string BuyingPrice {
            get {
                return ResourceManager.GetString("BuyingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby expressly acknowledge that {0} is a digital non-returnable and non-refundable product for which right of withdrawal is not applicable. I have checked the details above and confirm that these are correct. Also I agree to the {1}..
        /// </summary>
        public static string BuyInitiatedCheckboxText1a {
            get {
                return ResourceManager.GetString("BuyInitiatedCheckboxText1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string BuyInitiatedCheckboxText1b {
            get {
                return ResourceManager.GetString("BuyInitiatedCheckboxText1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account holders can almost instantly buy {0} using the applicable online instant payment method (iDeal, Bancontact Mister Cash, GiroPay, MyBank, Sofort and Interac). Within a few minutes you will automatically receive the {0} you ordered in your private {0} wallet. Note: some transactions may have a send delay..
        /// </summary>
        public static string BuyInstantPaymentText1 {
            get {
                return ResourceManager.GetString("BuyInstantPaymentText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact amount of {0} you can puchase for the selected amount of money is dynamically updated above (refreshes every minute) according to the real-time buy price. When you click the Review Order button, the {0} buy price will be locked and the lock in period is displayed. This way you know exactly how many {0} you will receive in your wallet. After clicking the Review Order button we advise you to continue your checkout without delay. If your payment takes more than the lock in period to finalise, your {0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuyInstantPaymentText2 {
            get {
                return ResourceManager.GetString("BuyInstantPaymentText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {0} with online instant payment method.
        /// </summary>
        public static string BuyInstantPaymentTitle {
            get {
                return ResourceManager.GetString("BuyInstantPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow steps to add a new {0} address to an existing account..
        /// </summary>
        public static string BuyPageAddAddressDescription {
            get {
                return ResourceManager.GetString("BuyPageAddAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string BuyPageAddAddressLink {
            get {
                return ResourceManager.GetString("BuyPageAddAddressLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} address.
        /// </summary>
        public static string BuyPageAddAddressTitle {
            get {
                return ResourceManager.GetString("BuyPageAddAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2 minutes you can create and activate your first account..
        /// </summary>
        public static string BuyPageCreateAccountDescription {
            get {
                return ResourceManager.GetString("BuyPageCreateAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string BuyPageCreateAccountLink {
            get {
                return ResourceManager.GetString("BuyPageCreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string BuyPageCreateAccountTitle {
            get {
                return ResourceManager.GetString("BuyPageCreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy service temporary not available..
        /// </summary>
        public static string BuyPageErrorText {
            get {
                return ResourceManager.GetString("BuyPageErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {0}.
        /// </summary>
        public static string BuyPageTabTitle {
            get {
                return ResourceManager.GetString("BuyPageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Welcome to Hermes!&lt;/h4&gt;
        ///
        ///&lt;p&gt;To raise your buy and sell limits, we require a first (test) transaction.&lt;/p&gt;.
        /// </summary>
        public static string BuyPageTestTransactionNotice {
            get {
                return ResourceManager.GetString("BuyPageTestTransactionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s buy.
        /// </summary>
        public static string BuyPageTitle {
            get {
                return ResourceManager.GetString("BuyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction costs consist of a service fee, a miners (network) fee and a bank fee. You will receive a confirmation email with the transaction details after the {0} have been sent to your wallet..
        /// </summary>
        public static string BuyTransactionCostText1 {
            get {
                return ResourceManager.GetString("BuyTransactionCostText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction currently not possible, buying transactions have been disabled.
        /// </summary>
        public static string BuyTransactionsAreDisabled {
            get {
                return ResourceManager.GetString("BuyTransactionsAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated transaction buy value exceeding daily limit.
        /// </summary>
        public static string CustomerBuyLimitPerDayExceeded {
            get {
                return ResourceManager.GetString("CustomerBuyLimitPerDayExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated transaction buy value exceeding monthy limit.
        /// </summary>
        public static string CustomerBuyLimitPerMonthExceeded {
            get {
                return ResourceManager.GetString("CustomerBuyLimitPerMonthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is currently not active.
        /// </summary>
        public static string ExchangeInactive {
            get {
                return ResourceManager.GetString("ExchangeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction buy value too large.
        /// </summary>
        public static string FiatAmountAboveMaximumBuyLimit {
            get {
                return ResourceManager.GetString("FiatAmountAboveMaximumBuyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method is limited. Please try another payment method for larger amounts..
        /// </summary>
        public static string FiatAmountAboveMaximumPaymentMethodBuyLimit {
            get {
                return ResourceManager.GetString("FiatAmountAboveMaximumPaymentMethodBuyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction buy value too small.
        /// </summary>
        public static string FiatAmountBelowMinimumBuyAmount {
            get {
                return ResourceManager.GetString("FiatAmountBelowMinimumBuyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this payment method our payment processor requires us to collect an Id of the clients. To activate this payment option please send a photo of your passport, id-card or drivers license. Please also provide your account code. Thanks for your understanding..
        /// </summary>
        public static string FotoIdentificationRequired {
            get {
                return ResourceManager.GetString("FotoIdentificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code:.
        /// </summary>
        public static string InitiateAccountCodeLabel {
            get {
                return ResourceManager.GetString("InitiateAccountCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name:.
        /// </summary>
        public static string InitiateAccountNameLabel {
            get {
                return ResourceManager.GetString("InitiateAccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string InitiateAddressLabel {
            get {
                return ResourceManager.GetString("InitiateAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank account:.
        /// </summary>
        public static string InitiateBankAccountLabel {
            get {
                return ResourceManager.GetString("InitiateBankAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC code:.
        /// </summary>
        public static string InitiateBICCodeLabel {
            get {
                return ResourceManager.GetString("InitiateBICCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - please check the account details -.
        /// </summary>
        public static string InitiateCheckDetailsMessage {
            get {
                return ResourceManager.GetString("InitiateCheckDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details.
        /// </summary>
        public static string InitiateDetailsTitle {
            get {
                return ResourceManager.GetString("InitiateDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email:.
        /// </summary>
        public static string InitiateEmailLabel {
            get {
                return ResourceManager.GetString("InitiateEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated purchase amount:.
        /// </summary>
        public static string InitiateEstimatedPurchaseLabel {
            get {
                return ResourceManager.GetString("InitiateEstimatedPurchaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate Payment.
        /// </summary>
        public static string InitiatePageTabTitle {
            get {
                return ResourceManager.GetString("InitiatePageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate Payment.
        /// </summary>
        public static string InitiatePageTitle {
            get {
                return ResourceManager.GetString("InitiatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment comment:.
        /// </summary>
        public static string InitiatePaymentReferenceLabel {
            get {
                return ResourceManager.GetString("InitiatePaymentReferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate bank transaction.
        /// </summary>
        public static string InitiatePaymentSubmitButton {
            get {
                return ResourceManager.GetString("InitiatePaymentSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase amount:.
        /// </summary>
        public static string InitiatePurchaseAmountLabel {
            get {
                return ResourceManager.GetString("InitiatePurchaseAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected exchange:.
        /// </summary>
        public static string InitiateSelectedExchageLabel {
            get {
                return ResourceManager.GetString("InitiateSelectedExchageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: For this payment method our payment processor requires a holding period before we can send the {0} to you. The {0} will therefor be automatically sent to your wallet {1} hours after you finish the payment..
        /// </summary>
        public static string InitiateSendDelayInfo1 {
            get {
                return ResourceManager.GetString("InitiateSendDelayInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: For this payment method our payment processor requires a holding period before we can send the {0} to you. The {0} will therefor be automatically sent to your wallet after your payment is settled with our bank (typically 1 or 2 working days)..
        /// </summary>
        public static string InitiateSendDelayInfo2 {
            get {
                return ResourceManager.GetString("InitiateSendDelayInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account:.
        /// </summary>
        public static string InitiateSEPABankAccountLabel {
            get {
                return ResourceManager.GetString("InitiateSEPABankAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate your bank transfer from the bank account connected to your Account..
        /// </summary>
        public static string InitiateSEPACondition1 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfers not in line with these terms will be returned (after deduction of bank costs)..
        /// </summary>
        public static string InitiateSEPACondition10 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put your Account code in the &apos;comment&apos; (sometimes called &apos;label&apos; or &apos;reference&apos;) field of the bank transaction..
        /// </summary>
        public static string InitiateSEPACondition2 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only transfer Euro amounts within the limits of your Account trust level..
        /// </summary>
        public static string InitiateSEPACondition3 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions using New Account are limited to {0} Euro equivalent per day..
        /// </summary>
        public static string InitiateSEPACondition4 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After your SEPA bank transfer, it takes 1-3 working days to show on our bank account..
        /// </summary>
        public static string InitiateSEPACondition5 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once our bank confirms your transfer, we initiate a buy transaction and the {0} will be sent to your wallet..
        /// </summary>
        public static string InitiateSEPACondition6 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The estimated purchase amount of {0} is based on the current buy price. The final amount of {0} you receive will differ from the estimate as the {0} price is determined when your order is actually traded..
        /// </summary>
        public static string InitiateSEPACondition7 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InitiateSEPACondition8 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your {0} are sent to your wallet you will receive a confirmation email with the financial transaction details..
        /// </summary>
        public static string InitiateSEPACondition9 {
            get {
                return ResourceManager.GetString("InitiateSEPACondition9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When buying {0} by SEPA bank transfer, you acknowledge and agree to accept:.
        /// </summary>
        public static string InitiateSEPAConditionsMessage {
            get {
                return ResourceManager.GetString("InitiateSEPAConditionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONS.
        /// </summary>
        public static string InitiateSEPAConditionsTitle {
            get {
                return ResourceManager.GetString("InitiateSEPAConditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank details for SEPA bank transfer.
        /// </summary>
        public static string InitiateSEPAPaymentTitle {
            get {
                return ResourceManager.GetString("InitiateSEPAPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only payments that origin from the same bank account as stated in your account details can be processed. Please create a new account if you want to use a different bank account..
        /// </summary>
        public static string InitiateTransactionBankAccountWarning {
            get {
                return ResourceManager.GetString("InitiateTransactionBankAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction code:.
        /// </summary>
        public static string InitiateTransactionCodeLabel {
            get {
                return ResourceManager.GetString("InitiateTransactionCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details.
        /// </summary>
        public static string InitiateTransactionDetailsTitle {
            get {
                return ResourceManager.GetString("InitiateTransactionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction timestamp:.
        /// </summary>
        public static string InitiateTransactionTimeLabel {
            get {
                return ResourceManager.GetString("InitiateTransactionTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} price for this transaction has been locked in for the next {1} minutes, so you know exactly how many {0} you will receive (purchase amount). We advise you to continue your checkout without delay. You will receive a confirmation email with the financial transaction details after your {0} are sent to your wallet..
        /// </summary>
        public static string InitiateTransactionTimeText1 {
            get {
                return ResourceManager.GetString("InitiateTransactionTimeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your payment takes more than {0} minutes, your {1} price will be updated with the actual buy price at the time of receiving your payment signal. In that case the final amount of {1} sent to your wallet may differ slightly..
        /// </summary>
        public static string InitiateTransactionTimeText2 {
            get {
                return ResourceManager.GetString("InitiateTransactionTimeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The estimated purchase amount is based on the current buy price. The final amount of {0} sent to your wallet may differ slightly. You will receive a confirmation email with the financial transaction details after your {0} are sent to your wallet..
        /// </summary>
        public static string InitiateTransactionTimeText3 {
            get {
                return ResourceManager.GetString("InitiateTransactionTimeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction value:.
        /// </summary>
        public static string InitiateTransactionValueLabel {
            get {
                return ResourceManager.GetString("InitiateTransactionValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wallet address:.
        /// </summary>
        public static string InitiateWalletAddressLabel {
            get {
                return ResourceManager.GetString("InitiateWalletAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank BIC code:.
        /// </summary>
        public static string InitiateYourBICCodeLabel {
            get {
                return ResourceManager.GetString("InitiateYourBICCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only initiate one test transaction per day.
        /// </summary>
        public static string MaximumNumberOfTestTransactionExceeded {
            get {
                return ResourceManager.GetString("MaximumNumberOfTestTransactionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment method available.
        /// </summary>
        public static string PaymentMethodNotFound {
            get {
                return ResourceManager.GetString("PaymentMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save payment information.
        /// </summary>
        public static string PSP3DSecureNotAvailable {
            get {
                return ResourceManager.GetString("PSP3DSecureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save payment information.
        /// </summary>
        public static string PSPClientIdNotFound {
            get {
                return ResourceManager.GetString("PSPClientIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save payment service provider information.
        /// </summary>
        public static string PSPInformationNotSaved {
            get {
                return ResourceManager.GetString("PSPInformationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service provider misses initiation URL.
        /// </summary>
        public static string PSPInitiateURLNotFound {
            get {
                return ResourceManager.GetString("PSPInitiateURLNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service provider sent invalid checksum.
        /// </summary>
        public static string PSPInvalidChecksum {
            get {
                return ResourceManager.GetString("PSPInvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected payment method failed to initiate a transaction, please contact support.
        /// </summary>
        public static string PSPInvalidPaymentResponse {
            get {
                return ResourceManager.GetString("PSPInvalidPaymentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service provider sent invalid status code.
        /// </summary>
        public static string PSPInvalidStatusCode {
            get {
                return ResourceManager.GetString("PSPInvalidStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service provider received a request with missing parameters.
        /// </summary>
        public static string PSPMissingParameters {
            get {
                return ResourceManager.GetString("PSPMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment service provider initiation URL is not available.
        /// </summary>
        public static string PSPRedirectURLNotAvailable {
            get {
                return ResourceManager.GetString("PSPRedirectURLNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register creditcard.
        /// </summary>
        public static string RegisterCreditCardButton {
            get {
                return ResourceManager.GetString("RegisterCreditCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card registration.
        /// </summary>
        public static string RegisterCreditCardText {
            get {
                return ResourceManager.GetString("RegisterCreditCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For questions or additional information you can contact:.
        /// </summary>
        public static string ReturnContactLabel {
            get {
                return ResourceManager.GetString("ReturnContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was not completed with the following reason:.
        /// </summary>
        public static string ReturnMessageError {
            get {
                return ResourceManager.GetString("ReturnMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was &lt;b&gt;successfully&lt;/b&gt; completed. In a few minutes you will receive your {0} and an email with the financial details..
        /// </summary>
        public static string ReturnMessageSuccess {
            get {
                return ResourceManager.GetString("ReturnMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was &lt;b&gt;successfully&lt;/b&gt; completed. In a few minutes you will receive an email with the financial details..
        /// </summary>
        public static string ReturnMessageSuccessWithDelay {
            get {
                return ResourceManager.GetString("ReturnMessageSuccessWithDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was &lt;b&gt;successfully&lt;/b&gt; completed. In a few minutes you will receive an email with the financial details..
        /// </summary>
        public static string ReturnMessageSuccessWithOptionalDelay {
            get {
                return ResourceManager.GetString("ReturnMessageSuccessWithOptionalDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Result.
        /// </summary>
        public static string ReturnPageTabTitle {
            get {
                return ResourceManager.GetString("ReturnPageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} payment response.
        /// </summary>
        public static string ReturnPageTitle {
            get {
                return ResourceManager.GetString("ReturnPageTitle", resourceCulture);
            }
        }
    }
}
