//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Samples.Broker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SellPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SellPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Samples.Broker.Resources.SellPages", typeof(SellPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string RequestReturnButtonConfirm {
            get {
                return ResourceManager.GetString("RequestReturnButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction has already been returned or is no longer valid..
        /// </summary>
        public static string RequestReturnFail {
            get {
                return ResourceManager.GetString("RequestReturnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the {0} address to receive your {0} back and click the confirm button:.
        /// </summary>
        public static string RequestReturnFormText {
            get {
                return ResourceManager.GetString("RequestReturnFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The automatically selected {0} address to receive your {0} back is the one connected to the account that you used to sell the {0}. Alternatively you can select a {0} address from one of your other active accounts if you have more than one..
        /// </summary>
        public static string RequestReturnInfo1 {
            get {
                return ResourceManager.GetString("RequestReturnInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to receive your {0} back on yet another {0} address, you can create an.
        /// </summary>
        public static string RequestReturnInfo2a {
            get {
                return ResourceManager.GetString("RequestReturnInfo2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with a new {0} address first, and reopen this page with the link in your email..
        /// </summary>
        public static string RequestReturnInfo2b {
            get {
                return ResourceManager.GetString("RequestReturnInfo2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning reason:.
        /// </summary>
        public static string RequestReturnReason {
            get {
                return ResourceManager.GetString("RequestReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} return addres has been successful confirmed. After 6 blockchain confirmations you will receive your {0} back..
        /// </summary>
        public static string RequestReturnSuccessInfo1 {
            get {
                return ResourceManager.GetString("RequestReturnSuccessInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed {0} return address.
        /// </summary>
        public static string RequestReturnSuccessTitle {
            get {
                return ResourceManager.GetString("RequestReturnSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning your {0}.
        /// </summary>
        public static string RequestReturnTitle {
            get {
                return ResourceManager.GetString("RequestReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling of {0} temporary not available.
        /// </summary>
        public static string SELLERRORCODE001 {
            get {
                return ResourceManager.GetString("SELLERRORCODE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account unknown or not active.
        /// </summary>
        public static string SELLERRORCODE002 {
            get {
                return ResourceManager.GetString("SELLERRORCODE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daily or monthly sell limit of this account has been reached.
        /// </summary>
        public static string SELLERRORCODE003 {
            get {
                return ResourceManager.GetString("SELLERRORCODE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell transaction size too small.
        /// </summary>
        public static string SELLERRORCODE004 {
            get {
                return ResourceManager.GetString("SELLERRORCODE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} sell method available for this account.
        /// </summary>
        public static string SELLERRORCODE005 {
            get {
                return ResourceManager.GetString("SELLERRORCODE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is temporary not active, please try again.
        /// </summary>
        public static string SELLERRORCODE006 {
            get {
                return ResourceManager.GetString("SELLERRORCODE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is temporary not active, please try again.
        /// </summary>
        public static string SELLERRORCODE007 {
            get {
                return ResourceManager.GetString("SELLERRORCODE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exchange service is temporary not active, please try again.
        /// </summary>
        public static string SELLERRORCODE008 {
            get {
                return ResourceManager.GetString("SELLERRORCODE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction currently not possible, selling transactions have been disabled.
        /// </summary>
        public static string SELLERRORCODE009 {
            get {
                return ResourceManager.GetString("SELLERRORCODE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save transaction.
        /// </summary>
        public static string SELLERRORCODE010 {
            get {
                return ResourceManager.GetString("SELLERRORCODE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code.
        /// </summary>
        public static string SellFormAccountLabel {
            get {
                return ResourceManager.GetString("SellFormAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account code.
        /// </summary>
        public static string SellFormAccountPlaceHolder {
            get {
                return ResourceManager.GetString("SellFormAccountPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string SellFormAmountLabel {
            get {
                return ResourceManager.GetString("SellFormAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank fee.
        /// </summary>
        public static string SellFormBankFeeLabel {
            get {
                return ResourceManager.GetString("SellFormBankFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string SellFormCheckAccountButton {
            get {
                return ResourceManager.GetString("SellFormCheckAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited business account.
        /// </summary>
        public static string SellFormLimitedBusinessMessage {
            get {
                return ResourceManager.GetString("SellFormLimitedBusinessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is this account limited?.
        /// </summary>
        public static string SellFormLimitedInfoLink {
            get {
                return ResourceManager.GetString("SellFormLimitedInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited personal account.
        /// </summary>
        public static string SellFormLimitedPersonalMessage {
            get {
                return ResourceManager.GetString("SellFormLimitedPersonalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need verification?.
        /// </summary>
        public static string SellFormNeedVerificationLink {
            get {
                return ResourceManager.GetString("SellFormNeedVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified business account..
        /// </summary>
        public static string SellFormNewBusiness {
            get {
                return ResourceManager.GetString("SellFormNewBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New business account.
        /// </summary>
        public static string SellFormNewBusinessMessage {
            get {
                return ResourceManager.GetString("SellFormNewBusinessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New personal account..
        /// </summary>
        public static string SellFormNewPersonal {
            get {
                return ResourceManager.GetString("SellFormNewPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code?.
        /// </summary>
        public static string SellFormNoActiveAccountLink {
            get {
                return ResourceManager.GetString("SellFormNoActiveAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an active account!.
        /// </summary>
        public static string SellFormNotActiveAccount {
            get {
                return ResourceManager.GetString("SellFormNotActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout.
        /// </summary>
        public static string SellFormPayoutLabel {
            get {
                return ResourceManager.GetString("SellFormPayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review order.
        /// </summary>
        public static string SellFormReviewButton {
            get {
                return ResourceManager.GetString("SellFormReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee.
        /// </summary>
        public static string SellFormServiceFeeLabel {
            get {
                return ResourceManager.GetString("SellFormServiceFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Welcome to HERMES!&lt;/h4&gt;
        ///    Before you can start to sell {0}, you first need to complete a small test buy transaction. This is to verify your banking details..
        /// </summary>
        public static string SellFormStatusNotice1 {
            get {
                return ResourceManager.GetString("SellFormStatusNotice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully completed your first buy transaction. As soon as your payment arrives on our bank account you can start to sell {0}. This will typically take one working-day. Thanks for your understanding..
        /// </summary>
        public static string SellFormStatusNotice2 {
            get {
                return ResourceManager.GetString("SellFormStatusNotice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can start to sell {0}, you first need to upload your FotoID. After it has been checked you can start selling {0}. This will typically take one working-day. Thanks for your understanding..
        /// </summary>
        public static string SellFormStatusNotice3 {
            get {
                return ResourceManager.GetString("SellFormStatusNotice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string SellFormSubTotalLabel {
            get {
                return ResourceManager.GetString("SellFormSubTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted personal account..
        /// </summary>
        public static string SellFormTrustedPersonal {
            get {
                return ResourceManager.GetString("SellFormTrustedPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted personal account.
        /// </summary>
        public static string SellFormTrustedPersonalMessage {
            get {
                return ResourceManager.GetString("SellFormTrustedPersonalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified business account..
        /// </summary>
        public static string SellFormVerifiedBusiness {
            get {
                return ResourceManager.GetString("SellFormVerifiedBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified personal account..
        /// </summary>
        public static string SellFormVerifiedPersonal {
            get {
                return ResourceManager.GetString("SellFormVerifiedPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid {0} account.
        /// </summary>
        public static string SellFormWrongCoinAccount {
            get {
                return ResourceManager.GetString("SellFormWrongCoinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling price.
        /// </summary>
        public static string SellingPrice {
            get {
                return ResourceManager.GetString("SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account:.
        /// </summary>
        public static string SellInitiateAccountBank {
            get {
                return ResourceManager.GetString("SellInitiateAccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code:.
        /// </summary>
        public static string SellInitiateAccountCode {
            get {
                return ResourceManager.GetString("SellInitiateAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string SellInitiateAccountEmail {
            get {
                return ResourceManager.GetString("SellInitiateAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        public static string SellInitiateAccountTitle {
            get {
                return ResourceManager.GetString("SellInitiateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: fill in your account code {0} into the memo field when creating the transaction, else we cannot pay out your Lumens!.
        /// </summary>
        public static string SellInitiateLumenWarning {
            get {
                return ResourceManager.GetString("SellInitiateLumenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-code of this transaction:.
        /// </summary>
        public static string SellInitiateQRCode {
            get {
                return ResourceManager.GetString("SellInitiateQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-code of this address:.
        /// </summary>
        public static string SellInitiateQRCodeAddress {
            get {
                return ResourceManager.GetString("SellInitiateQRCodeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SellInitiateSendTextA {
            get {
                return ResourceManager.GetString("SellInitiateSendTextA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to your sell address:.
        /// </summary>
        public static string SellInitiateSendTextB {
            get {
                return ResourceManager.GetString("SellInitiateSendTextB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate {0} sell transaction.
        /// </summary>
        public static string SellInitiateTabTitle {
            get {
                return ResourceManager.GetString("SellInitiateTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} price for this transaction has been locked in for the next {1} minutes, so you know exactly what your payout value will be. We advise you to continue your checkout without delay. You will receive a confirmation email with the financial transaction details after your {0} have been traded..
        /// </summary>
        public static string SellInitiateText1 {
            get {
                return ResourceManager.GetString("SellInitiateText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (If your transaction takes more than {1} minutes, your {0} price will be updated with the actual sell price at the time of receiving your {0}. In that case the payout value may differ slightly.).
        /// </summary>
        public static string SellInitiateText2 {
            get {
                return ResourceManager.GetString("SellInitiateText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payout value is an estimate based on the current sell price. The final sell price may differ slightly as it is updated by the actual price at the time of receiving your {0}. You will receive a confirmation email with the financial transaction details after your {0} are traded..
        /// </summary>
        public static string SellInitiateText3 {
            get {
                return ResourceManager.GetString("SellInitiateText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you execute your sell transaction with the right network fee for a quick confirmation of your transaction..
        /// </summary>
        public static string SellInitiateTextNetworkFee {
            get {
                return ResourceManager.GetString("SellInitiateTextNetworkFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate {0} sell transaction.
        /// </summary>
        public static string SellInitiateTitle {
            get {
                return ResourceManager.GetString("SellInitiateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell amount:.
        /// </summary>
        public static string SellInitiateTransactionAmount {
            get {
                return ResourceManager.GetString("SellInitiateTransactionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction code:.
        /// </summary>
        public static string SellInitiateTransactionCode {
            get {
                return ResourceManager.GetString("SellInitiateTransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout estimate:.
        /// </summary>
        public static string SellInitiateTransactionEstimate {
            get {
                return ResourceManager.GetString("SellInitiateTransactionEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected exchange:.
        /// </summary>
        public static string SellInitiateTransactionExchange {
            get {
                return ResourceManager.GetString("SellInitiateTransactionExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout value:.
        /// </summary>
        public static string SellInitiateTransactionPayout {
            get {
                return ResourceManager.GetString("SellInitiateTransactionPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction timestamp:.
        /// </summary>
        public static string SellInitiateTransactionTimestamp {
            get {
                return ResourceManager.GetString("SellInitiateTransactionTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details.
        /// </summary>
        public static string SellInitiateTransactionTitle {
            get {
                return ResourceManager.GetString("SellInitiateTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow steps to add a new {0} address to an existing account..
        /// </summary>
        public static string SellPageAddAddressDescription {
            get {
                return ResourceManager.GetString("SellPageAddAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string SellPageAddAddressLink {
            get {
                return ResourceManager.GetString("SellPageAddAddressLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} address.
        /// </summary>
        public static string SellPageAddAddressTitle {
            get {
                return ResourceManager.GetString("SellPageAddAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2 minutes you can create and activate your first account..
        /// </summary>
        public static string SellPageCreateAccountDescription {
            get {
                return ResourceManager.GetString("SellPageCreateAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string SellPageCreateAccountLink {
            get {
                return ResourceManager.GetString("SellPageCreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string SellPageCreateAccountTitle {
            get {
                return ResourceManager.GetString("SellPageCreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you initiate a Sell transaction through this page, the {0} price for your transaction will be locked in for a few minutes. We advise you to continue your checkout without delay. If your transaction takes more than the lock in period to finalise, your {0} price will be updated with the actual sell price at the time of receiving your {0}. In that case your payout may differ slightly..
        /// </summary>
        public static string SellPageExplainText1 {
            get {
                return ResourceManager.GetString("SellPageExplainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively if you don&apos;t use the Sell form on this page to lock your {0} price, your {0} will automatically be traded when the transaction is received..
        /// </summary>
        public static string SellPageExplainText2 {
            get {
                return ResourceManager.GetString("SellPageExplainText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In either case you need to send your {0} from your wallet to the specific {0} address which is connected to your Account. You received this address when you created your Account. You can also view this address after clicking the Review Order button..
        /// </summary>
        public static string SellPageExplainText3 {
            get {
                return ResourceManager.GetString("SellPageExplainText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only send an amount of {0} within the limits of your Account. You can check your limits by submitting your Account Code above. If you send {0} in excess of your limits, the whole transaction (after your confirmation) will be returned to a return address connected to one of your Accounts (with deduction of a small {0} penalty to pay for transaction costs)..
        /// </summary>
        public static string SellPageExplainText4 {
            get {
                return ResourceManager.GetString("SellPageExplainText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After receiving at least 3 confirmations the payout procedure is initiated. When sending {0}, don&apos;t forget to add a network transaction fee for the miners. Otherwise confirmations can be slow and your payout might get delayed..
        /// </summary>
        public static string SellPageExplainText5 {
            get {
                return ResourceManager.GetString("SellPageExplainText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction costs consist of a service fee, a miners (network) fee and a bank fee. You will receive a confirmation email with the transaction details after your {0} have been traded. The payout procedure of the resulting funds to your bank account runs every working day at 12:00 for all European banks..
        /// </summary>
        public static string SellPageExplainText6 {
            get {
                return ResourceManager.GetString("SellPageExplainText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch bank account..
        /// </summary>
        public static string SellPageListText11 {
            get {
                return ResourceManager.GetString("SellPageListText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account with any bank in the Single European Payments Area (SEPA)..
        /// </summary>
        public static string SellPageListText12 {
            get {
                return ResourceManager.GetString("SellPageListText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds on your bank account same day..
        /// </summary>
        public static string SellPageListText21 {
            get {
                return ResourceManager.GetString("SellPageListText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds on your bank account within 1-3 working days (depending on bank)..
        /// </summary>
        public static string SellPageListText22 {
            get {
                return ResourceManager.GetString("SellPageListText22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds on your bank account next working day..
        /// </summary>
        public static string SellPageListText31 {
            get {
                return ResourceManager.GetString("SellPageListText31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds on your bank account within 1-3 working days (depending on bank)..
        /// </summary>
        public static string SellPageListText32 {
            get {
                return ResourceManager.GetString("SellPageListText32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout schedule.
        /// </summary>
        public static string SellPageListTitle1 {
            get {
                return ResourceManager.GetString("SellPageListTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} received and confirmed on working days before 12:00 CET.
        /// </summary>
        public static string SellPageListTitle2 {
            get {
                return ResourceManager.GetString("SellPageListTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} received and confirmed on working days after 12:00 CET or weekend/holidays.
        /// </summary>
        public static string SellPageListTitle3 {
            get {
                return ResourceManager.GetString("SellPageListTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} return address successful confirmed.
        /// </summary>
        public static string SellPageReturnSuccessTabTitle {
            get {
                return ResourceManager.GetString("SellPageReturnSuccessTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning your {0}.
        /// </summary>
        public static string SellPageReturnTabTitle {
            get {
                return ResourceManager.GetString("SellPageReturnTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell service temporary not available..
        /// </summary>
        public static string SellPageServiceNotAvailable {
            get {
                return ResourceManager.GetString("SellPageServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell {0}.
        /// </summary>
        public static string SellPageTabTitle {
            get {
                return ResourceManager.GetString("SellPageTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s sell.
        /// </summary>
        public static string SellPageTitle {
            get {
                return ResourceManager.GetString("SellPageTitle", resourceCulture);
            }
        }
    }
}
