//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Samples.Broker.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Site {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nexus.Samples.Broker.Resources.Site", typeof(Site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FooterAMLPolicyLink {
            get {
                return ResourceManager.GetString("FooterAMLPolicyLink", resourceCulture);
            }
        }
        
        public static string FooterContactLink {
            get {
                return ResourceManager.GetString("FooterContactLink", resourceCulture);
            }
        }
        
        public static string FooterCopyRight {
            get {
                return ResourceManager.GetString("FooterCopyRight", resourceCulture);
            }
        }
        
        public static string FooterCreateAccountLink {
            get {
                return ResourceManager.GetString("FooterCreateAccountLink", resourceCulture);
            }
        }
        
        public static string FooterHomeLink {
            get {
                return ResourceManager.GetString("FooterHomeLink", resourceCulture);
            }
        }
        
        public static string FooterHowToBuyLink {
            get {
                return ResourceManager.GetString("FooterHowToBuyLink", resourceCulture);
            }
        }
        
        public static string FooterHowToSellLink {
            get {
                return ResourceManager.GetString("FooterHowToSellLink", resourceCulture);
            }
        }
        
        public static string FooterLinksLink {
            get {
                return ResourceManager.GetString("FooterLinksLink", resourceCulture);
            }
        }
        
        public static string FooterMarketPricesChartsLink {
            get {
                return ResourceManager.GetString("FooterMarketPricesChartsLink", resourceCulture);
            }
        }
        
        public static string FooterPoweredBy {
            get {
                return ResourceManager.GetString("FooterPoweredBy", resourceCulture);
            }
        }
        
        public static string FooterPrivacyPolicyLink {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyLink", resourceCulture);
            }
        }
        
        public static string FooterReviewsLink {
            get {
                return ResourceManager.GetString("FooterReviewsLink", resourceCulture);
            }
        }
        
        public static string FooterTermsOfUseLink {
            get {
                return ResourceManager.GetString("FooterTermsOfUseLink", resourceCulture);
            }
        }
        
        public static string MenuAccount {
            get {
                return ResourceManager.GetString("MenuAccount", resourceCulture);
            }
        }
        
        public static string MenuAccountAdditional {
            get {
                return ResourceManager.GetString("MenuAccountAdditional", resourceCulture);
            }
        }
        
        public static string MenuAccountCreate {
            get {
                return ResourceManager.GetString("MenuAccountCreate", resourceCulture);
            }
        }
        
        public static string MenuAccountDelete {
            get {
                return ResourceManager.GetString("MenuAccountDelete", resourceCulture);
            }
        }
        
        public static string MenuAccountForgotten {
            get {
                return ResourceManager.GetString("MenuAccountForgotten", resourceCulture);
            }
        }
        
        public static string MenuBlog {
            get {
                return ResourceManager.GetString("MenuBlog", resourceCulture);
            }
        }
        
        public static string MenuBuy {
            get {
                return ResourceManager.GetString("MenuBuy", resourceCulture);
            }
        }
        
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        public static string MenuPrice {
            get {
                return ResourceManager.GetString("MenuPrice", resourceCulture);
            }
        }
        
        public static string MenuSell {
            get {
                return ResourceManager.GetString("MenuSell", resourceCulture);
            }
        }
        
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        public static string MenuFAQ {
            get {
                return ResourceManager.GetString("MenuFAQ", resourceCulture);
            }
        }
        
        public static string SideBarMarketPricesBuy {
            get {
                return ResourceManager.GetString("SideBarMarketPricesBuy", resourceCulture);
            }
        }
        
        public static string SideBarMarketPricesSell {
            get {
                return ResourceManager.GetString("SideBarMarketPricesSell", resourceCulture);
            }
        }
        
        public static string SideBarMarketPricesTitle {
            get {
                return ResourceManager.GetString("SideBarMarketPricesTitle", resourceCulture);
            }
        }
        
        public static string SideBarNewsFeedTitle {
            get {
                return ResourceManager.GetString("SideBarNewsFeedTitle", resourceCulture);
            }
        }
        
        public static string SideBarReviewsTitle {
            get {
                return ResourceManager.GetString("SideBarReviewsTitle", resourceCulture);
            }
        }
        
        public static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        public static string BuyPageDescription {
            get {
                return ResourceManager.GetString("BuyPageDescription", resourceCulture);
            }
        }
        
        public static string SellPageDescription {
            get {
                return ResourceManager.GetString("SellPageDescription", resourceCulture);
            }
        }
        
        public static string AccountPageDescription {
            get {
                return ResourceManager.GetString("AccountPageDescription", resourceCulture);
            }
        }
        
        public static string AditionalAccountPageDescription {
            get {
                return ResourceManager.GetString("AditionalAccountPageDescription", resourceCulture);
            }
        }
        
        public static string RequestInfoPageDescription {
            get {
                return ResourceManager.GetString("RequestInfoPageDescription", resourceCulture);
            }
        }
        
        public static string RequestDeletePageDescription {
            get {
                return ResourceManager.GetString("RequestDeletePageDescription", resourceCulture);
            }
        }
        
        public static string VerificationPageDescription {
            get {
                return ResourceManager.GetString("VerificationPageDescription", resourceCulture);
            }
        }
        
        public static string InfoPageDescription {
            get {
                return ResourceManager.GetString("InfoPageDescription", resourceCulture);
            }
        }
        
        public static string ChartsPageDescription {
            get {
                return ResourceManager.GetString("ChartsPageDescription", resourceCulture);
            }
        }
        
        public static string ReviewsPageDescription {
            get {
                return ResourceManager.GetString("ReviewsPageDescription", resourceCulture);
            }
        }
        
        public static string SupportPageDescription {
            get {
                return ResourceManager.GetString("SupportPageDescription", resourceCulture);
            }
        }
        
        public static string ContactPageDescription {
            get {
                return ResourceManager.GetString("ContactPageDescription", resourceCulture);
            }
        }
        
        public static string PrivacyPageDescription {
            get {
                return ResourceManager.GetString("PrivacyPageDescription", resourceCulture);
            }
        }
        
        public static string TermsPageDescription {
            get {
                return ResourceManager.GetString("TermsPageDescription", resourceCulture);
            }
        }
        
        public static string AMLPolicyPageDescription {
            get {
                return ResourceManager.GetString("AMLPolicyPageDescription", resourceCulture);
            }
        }
        
        public static string ErrorNotFoundTabTitle {
            get {
                return ResourceManager.GetString("ErrorNotFoundTabTitle", resourceCulture);
            }
        }
        
        public static string ErrorNotFoundText {
            get {
                return ResourceManager.GetString("ErrorNotFoundText", resourceCulture);
            }
        }
        
        public static string ErrorNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrorNotFoundTitle", resourceCulture);
            }
        }
        
        public static string ErrorTabTitle {
            get {
                return ResourceManager.GetString("ErrorTabTitle", resourceCulture);
            }
        }
        
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        public static string FooterInvestorsLink {
            get {
                return ResourceManager.GetString("FooterInvestorsLink", resourceCulture);
            }
        }
        
        public static string FooterPartnersLink {
            get {
                return ResourceManager.GetString("FooterPartnersLink", resourceCulture);
            }
        }
        
        public static string MenuLimit {
            get {
                return ResourceManager.GetString("MenuLimit", resourceCulture);
            }
        }
        
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        public static string SelectCrypto {
            get {
                return ResourceManager.GetString("SelectCrypto", resourceCulture);
            }
        }
        
        public static string FooterAccountInfo {
            get {
                return ResourceManager.GetString("FooterAccountInfo", resourceCulture);
            }
        }
        
        public static string FooterTradeMark {
            get {
                return ResourceManager.GetString("FooterTradeMark", resourceCulture);
            }
        }
        
        public static string FooterUnderApplication {
            get {
                return ResourceManager.GetString("FooterUnderApplication", resourceCulture);
            }
        }
        
        public static string PressLink {
            get {
                return ResourceManager.GetString("PressLink", resourceCulture);
            }
        }
        
        public static string FooterAddAddress {
            get {
                return ResourceManager.GetString("FooterAddAddress", resourceCulture);
            }
        }
        
        public static string FooterDeleteAccount {
            get {
                return ResourceManager.GetString("FooterDeleteAccount", resourceCulture);
            }
        }
        
        public static string FooterPressPage {
            get {
                return ResourceManager.GetString("FooterPressPage", resourceCulture);
            }
        }
        
        public static string FooterAccount {
            get {
                return ResourceManager.GetString("FooterAccount", resourceCulture);
            }
        }
        
        public static string FooterCrypto {
            get {
                return ResourceManager.GetString("FooterCrypto", resourceCulture);
            }
        }
        
        public static string NoAccountCode {
            get {
                return ResourceManager.GetString("NoAccountCode", resourceCulture);
            }
        }
    }
}
