//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Samples.Broker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Samples.Broker.Resources.Site", typeof(Site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account and start buying and selling digital currencies. Your account facilitates the use of the service and offers a one click ordering method..
        /// </summary>
        public static string AccountPageDescription {
            get {
                return ResourceManager.GetString("AccountPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create additional accounts which enables you to use multiple wallet addresses to receive your  digital currencies..
        /// </summary>
        public static string AditionalAccountPageDescription {
            get {
                return ResourceManager.GetString("AditionalAccountPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the services provided by HERMES are currently unregulated in The Netherlands, it is the Company&apos;s policy to comply with AML regulation..
        /// </summary>
        public static string AMLPolicyPageDescription {
            get {
                return ResourceManager.GetString("AMLPolicyPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With HERMES you can instantly buy  digital currencies using an online payment method, such as iDeal, Bancontact Mister Cash, Sofort or Interac. .
        /// </summary>
        public static string BuyPageDescription {
            get {
                return ResourceManager.GetString("BuyPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive charts with real-time prices, market depth and spread across multiple exchanges, including Bitstamp, BTC-e, Paymium, Kraken and ItBit..
        /// </summary>
        public static string ChartsPageDescription {
            get {
                return ResourceManager.GetString("ChartsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your language..
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or comments, please contact HERMES through our online contact form or alternatively by email..
        /// </summary>
        public static string ContactPageDescription {
            get {
                return ResourceManager.GetString("ContactPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string ErrorNotFoundTabTitle {
            get {
                return ResourceManager.GetString("ErrorNotFoundTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you are looking for something that isn&apos;t here..
        /// </summary>
        public static string ErrorNotFoundText {
            get {
                return ResourceManager.GetString("ErrorNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string ErrorNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrorNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTabTitle {
            get {
                return ResourceManager.GetString("ErrorTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string FooterAccount {
            get {
                return ResourceManager.GetString("FooterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        public static string FooterAccountInfo {
            get {
                return ResourceManager.GetString("FooterAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string FooterAddAddress {
            get {
                return ResourceManager.GetString("FooterAddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AML Policy.
        /// </summary>
        public static string FooterAMLPolicyLink {
            get {
                return ResourceManager.GetString("FooterAMLPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string FooterContactLink {
            get {
                return ResourceManager.GetString("FooterContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © copyright 2018 Digital Currency Services B.V.
        /// </summary>
        public static string FooterCopyRight {
            get {
                return ResourceManager.GetString("FooterCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string FooterCreateAccountLink {
            get {
                return ResourceManager.GetString("FooterCreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto.
        /// </summary>
        public static string FooterCrypto {
            get {
                return ResourceManager.GetString("FooterCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string FooterDeleteAccount {
            get {
                return ResourceManager.GetString("FooterDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string FooterHomeLink {
            get {
                return ResourceManager.GetString("FooterHomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to buy  digital currencies.
        /// </summary>
        public static string FooterHowToBuyLink {
            get {
                return ResourceManager.GetString("FooterHowToBuyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to sell  digital currencies.
        /// </summary>
        public static string FooterHowToSellLink {
            get {
                return ResourceManager.GetString("FooterHowToSellLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investors.
        /// </summary>
        public static string FooterInvestorsLink {
            get {
                return ResourceManager.GetString("FooterInvestorsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string FooterLinksLink {
            get {
                return ResourceManager.GetString("FooterLinksLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market price charts.
        /// </summary>
        public static string FooterMarketPricesChartsLink {
            get {
                return ResourceManager.GetString("FooterMarketPricesChartsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string FooterPartnersLink {
            get {
                return ResourceManager.GetString("FooterPartnersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by &lt;a href=&quot;http://www.quantoz.com/&quot; target=&quot;_blank&quot;&gt;Quantoz&lt;/a&gt;.
        /// </summary>
        public static string FooterPoweredBy {
            get {
                return ResourceManager.GetString("FooterPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string FooterPressPage {
            get {
                return ResourceManager.GetString("FooterPressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string FooterPrivacyPolicyLink {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string FooterReviewsLink {
            get {
                return ResourceManager.GetString("FooterReviewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string FooterTermsOfUseLink {
            get {
                return ResourceManager.GetString("FooterTermsOfUseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERMES® is a Community Trade Mark of Digital Currency Services B.V..
        /// </summary>
        public static string FooterTradeMark {
            get {
                return ResourceManager.GetString("FooterTradeMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under application of the Dutch National Bank.
        /// </summary>
        public static string FooterUnderApplication {
            get {
                return ResourceManager.GetString("FooterUnderApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERMES offers a safe, fast, transparent and cheap exchange service for individuals and businesses who wish to buy and/or sell  digital currencies..
        /// </summary>
        public static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short introduction and some links to help you get started..
        /// </summary>
        public static string InfoPageDescription {
            get {
                return ResourceManager.GetString("InfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MenuAccount {
            get {
                return ResourceManager.GetString("MenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string MenuAccountAdditional {
            get {
                return ResourceManager.GetString("MenuAccountAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string MenuAccountCreate {
            get {
                return ResourceManager.GetString("MenuAccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuAccountDelete {
            get {
                return ResourceManager.GetString("MenuAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten.
        /// </summary>
        public static string MenuAccountForgotten {
            get {
                return ResourceManager.GetString("MenuAccountForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string MenuBlog {
            get {
                return ResourceManager.GetString("MenuBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string MenuBuy {
            get {
                return ResourceManager.GetString("MenuBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string MenuFAQ {
            get {
                return ResourceManager.GetString("MenuFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string MenuLimit {
            get {
                return ResourceManager.GetString("MenuLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MenuPrice {
            get {
                return ResourceManager.GetString("MenuPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string MenuSell {
            get {
                return ResourceManager.GetString("MenuSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code?.
        /// </summary>
        public static string NoAccountCode {
            get {
                return ResourceManager.GetString("NoAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string PressLink {
            get {
                return ResourceManager.GetString("PressLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HERMES Privacy Policy informs you about which personal information is collected and how it may be used..
        /// </summary>
        public static string PrivacyPageDescription {
            get {
                return ResourceManager.GetString("PrivacyPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have full control over your Account. If required, simply request deletion of your Account and your details will be removed from our system..
        /// </summary>
        public static string RequestDeletePageDescription {
            get {
                return ResourceManager.GetString("RequestDeletePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon request we will send you an email with the Account info of all your active Accounts..
        /// </summary>
        public static string RequestInfoPageDescription {
            get {
                return ResourceManager.GetString("RequestInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HERMES values transparency and encourages clients to share opinions openly and contribute to the community. Reviews build credibility and reputation..
        /// </summary>
        public static string ReviewsPageDescription {
            get {
                return ResourceManager.GetString("ReviewsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a crypto.
        /// </summary>
        public static string SelectCrypto {
            get {
                return ResourceManager.GetString("SelectCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HERMES to sell your  digital currencies. Within a minute after receiving your digital currencies, HERMES trades them and sends the euros to your bank account..
        /// </summary>
        public static string SellPageDescription {
            get {
                return ResourceManager.GetString("SellPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY.
        /// </summary>
        public static string SideBarMarketPricesBuy {
            get {
                return ResourceManager.GetString("SideBarMarketPricesBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELL.
        /// </summary>
        public static string SideBarMarketPricesSell {
            get {
                return ResourceManager.GetString("SideBarMarketPricesSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCE PRICE.
        /// </summary>
        public static string SideBarMarketPricesTitle {
            get {
                return ResourceManager.GetString("SideBarMarketPricesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS FEED.
        /// </summary>
        public static string SideBarNewsFeedTitle {
            get {
                return ResourceManager.GetString("SideBarNewsFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        public static string SideBarReviewsTitle {
            get {
                return ResourceManager.GetString("SideBarReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse the HERMES FAQ for general bitcoin topics as well as specific content related to the HERMES services..
        /// </summary>
        public static string SupportPageDescription {
            get {
                return ResourceManager.GetString("SupportPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this Site, and further by registering to use our Services, you agree to accept and comply with the Terms of Use..
        /// </summary>
        public static string TermsPageDescription {
            get {
                return ResourceManager.GetString("TermsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To upgrade the trust status of your Account, please use the request form. You will receive an email with required documents for verification..
        /// </summary>
        public static string VerificationPageDescription {
            get {
                return ResourceManager.GetString("VerificationPageDescription", resourceCulture);
            }
        }
    }
}
